version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: healthcare-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_MULTIPLE_DATABASES: auth_db,users_db,appointments_db,payments_db,clinical_db,notifications_db,analytics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - healthcare-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: healthcare-redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - healthcare-network

  # Kafka Message Broker
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: healthcare-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - healthcare-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: healthcare-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - healthcare-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: healthcare-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - healthcare-network

  # MinIO (S3 compatible storage)
  minio:
    image: minio/minio:latest
    container_name: healthcare-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - healthcare-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: healthcare-auth-service
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: auth_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKERS: kafka:29092
      JWT_SECRET: super-secret-jwt-key-change-in-production
      JWT_EXPIRATION: 15m
      JWT_REFRESH_SECRET: super-secret-refresh-key-change-in-production
      JWT_REFRESH_EXPIRATION: 7d
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - healthcare-network

  # User Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: healthcare-user-service
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: users_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKERS: kafka:29092
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
      - kafka
      - minio
    networks:
      - healthcare-network

  # Appointment Service
  appointment-service:
    build:
      context: ./services/appointment-service
      dockerfile: Dockerfile
    container_name: healthcare-appointment-service
    environment:
      NODE_ENV: development
      PORT: 3005
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_NAME: appointments_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKER: kafka:29092
      JWT_SECRET: super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 3002
      NOTIFICATION_SERVICE_HOST: notification-service
      NOTIFICATION_SERVICE_PORT: 3006
    ports:
      - "3005:3005"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - healthcare-network

  # Payment Service
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: healthcare-payment-service
    environment:
      NODE_ENV: development
      PORT: 3004
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: payments_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKERS: kafka:29092
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    ports:
      - "3004:3004"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - healthcare-network

  # Clinical Service
  clinical-service:
    build:
      context: ./services/clinical-service
      dockerfile: Dockerfile
    container_name: healthcare-clinical-service
    environment:
      NODE_ENV: development
      PORT: 3006
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_NAME: clinical_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKER: kafka:29092
      JWT_SECRET: super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      ENCRYPTION_KEY: super-secret-encryption-key-change-in-production
    ports:
      - "3006:3006"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - healthcare-network

  # Notification Service
  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: healthcare-notification-service
    environment:
      NODE_ENV: development
      PORT: 3007
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: notifications_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKERS: kafka:29092
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
    ports:
      - "3007:3007"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - healthcare-network

  # Search Service
  search-service:
    build:
      context: ./services/search-service
      dockerfile: Dockerfile
    container_name: healthcare-search-service
    environment:
      NODE_ENV: development
      PORT: 3008
      ELASTICSEARCH_NODE: http://elasticsearch:9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKERS: kafka:29092
    ports:
      - "3008:3008"
    depends_on:
      - elasticsearch
      - redis
      - kafka
    networks:
      - healthcare-network

  # Video Service
  video-service:
    build:
      context: ./services/video-service
      dockerfile: Dockerfile
    container_name: healthcare-video-service
    environment:
      NODE_ENV: development
      PORT: 3009
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: video_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKERS: kafka:29092
      AGORA_APP_ID: ${AGORA_APP_ID}
      AGORA_APP_CERTIFICATE: ${AGORA_APP_CERTIFICATE}
    ports:
      - "3009:3009"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - healthcare-network

  # Analytics Service
  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    container_name: healthcare-analytics-service
    environment:
      NODE_ENV: development
      PORT: 3010
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: analytics_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      KAFKA_BROKERS: kafka:29092
      ELASTICSEARCH_NODE: http://elasticsearch:9200
    ports:
      - "3010:3010"
    depends_on:
      - postgres
      - redis
      - kafka
      - elasticsearch
    networks:
      - healthcare-network

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: healthcare-api-gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      USER_SERVICE_URL: http://user-service:3002
      APPOINTMENT_SERVICE_URL: http://appointment-service:3005
      PAYMENT_SERVICE_URL: http://payment-service:3004
      CLINICAL_SERVICE_URL: http://clinical-service:3006
      NOTIFICATION_SERVICE_URL: http://notification-service:3007
      SEARCH_SERVICE_URL: http://search-service:3008
      VIDEO_SERVICE_URL: http://video-service:3009
      ANALYTICS_SERVICE_URL: http://analytics-service:3010
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - appointment-service
      - payment-service
      - clinical-service
      - notification-service
      - search-service
      - video-service
      - analytics-service
    networks:
      - healthcare-network

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: healthcare-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - healthcare-network

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: healthcare-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    ports:
      - "3030:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./infrastructure/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - healthcare-network

  # Monitoring - Jaeger (Tracing)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: healthcare-jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  minio_data:
  prometheus_data:
  grafana_data: