global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'appointment-service'
    static_configs:
      - targets: ['appointment-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'clinical-service'
    static_configs:
      - targets: ['clinical-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3007']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:3008']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:3009']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3010']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
