name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push images
        run: |
          for service in auth user appointment payment clinical notification search video analytics gateway; do
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push \
              -t ${{ secrets.ECR_REGISTRY }}/health-platform-${service}:${{ github.ref_name }} \
              -t ${{ secrets.ECR_REGISTRY }}/health-platform-${service}:latest \
              ./services/${service}
          done

      - name: Update Kubernetes manifests
        run: |
          for service in auth user appointment payment clinical notification search video analytics gateway; do
            kubectl set image deployment/${service}-service \
              ${service}=${{ secrets.ECR_REGISTRY }}/health-platform-${service}:${{ github.ref_name }} \
              -n health-platform
          done

      - name: Wait for rollout
        run: |
          for service in auth user appointment payment clinical notification search video analytics gateway; do
            kubectl rollout status deployment/${service}-service -n health-platform
          done

      - name: Run smoke tests
        run: |
          npm run test:smoke

      - name: Notify deployment
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: 'Production deployment completed successfully!'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
